spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        generate_statistics: true
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.MySQL5Dialect
logging.level:
  org.hibernate.SQL: debug
decorator:
  datasource:
    p6spy:
      enable-logging: true
